# Generated by Django 4.2 on 2023-08-28 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_collaborator_user_id_alter_comment_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='prority',
            new_name='priority',
        ),
    ]
