# Generated by Django 4.2.4 on 2023-08-18 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_collaborator_user_id_alter_comment_user_id_and_more'),
        ('profiles', '0002_alter_user_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
